# Here we define the tree.
# The entire YAML file is a tree of dictionaries, except the very last
# node (leaves) - these are denoted as an array. Each item in the array
# points to another config file with the same sluggified name (Web Validators
# config lives in web-validators.yml)

Coding:
- Choosing a Programming Language
- Design Patterns

Development:
  Development Environment:
    Dvelopment Tools:
    - Editors
    - Web Validators
