intro: |
  This is a free text, and we can use Markdown here and newlines.

  **The intention is for this to be short** and just introduce the topic 
  at hand, if it is more than a couple of paragraphs, consider refactoring
  to a guide of its own.

guides:
- Text Editors Overview
- Choosing the Right Text Editors

topics:
- Sublime Text
- Eclipse
